//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;error&quot;:{&quot;code&quot;:499,&quot;message&quot;:&quot;Token required but not passed in the request.&quot;,&quot;details&quot;:[&quot;Token required.&quot;]}}.
        /// </summary>
        internal static string SampleGeocodeErrorResults {
            get {
                return ResourceManager.GetString("SampleGeocodeErrorResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;spatialReference&quot;:{&quot;wkid&quot;:102100,&quot;latestWkid&quot;:3857},&quot;candidates&quot;:[{&quot;address&quot;:&quot;James Madison Park&quot;,&quot;location&quot;:{&quot;x&quot;:-9950097.8754478674,&quot;y&quot;:5324273.9563675523},&quot;score&quot;:72.140000000000001,&quot;attributes&quot;:{&quot;Loc_name&quot;:&quot;World&quot;,&quot;Status&quot;:&quot;M&quot;,&quot;Score&quot;:72.140000000000001,&quot;Match_addr&quot;:&quot;James Madison Park&quot;,&quot;LongLabel&quot;:&quot;James Madison Park, 500 E Gorham St, Madison, WI, 53703, USA&quot;,&quot;ShortLabel&quot;:&quot;James Madison Park&quot;,&quot;Addr_type&quot;:&quot;POI&quot;,&quot;Type&quot;:&quot;Park&quot;,&quot;PlaceName&quot;:&quot;James Madison Park&quot;,&quot;Place_addr&quot;:&quot;500 E Gorham St, Madison, Wisc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleGeocodeSuccessResults {
            get {
                return ResourceManager.GetString("SampleGeocodeSuccessResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;directions&quot;: [
        ///        {
        ///            &quot;routeId&quot;: 1,
        ///            &quot;routeName&quot;: &quot;Location 1 - Location 2&quot;,
        ///            &quot;summary&quot;: {
        ///                &quot;totalLength&quot;: 0.547181119992593,
        ///                &quot;totalTime&quot;: 0.916666666666667,
        ///                &quot;totalDriveTime&quot;: 0.932502535171807,
        ///                &quot;envelope&quot;: {
        ///                    &quot;xmin&quot;: -122.408067,
        ///                    &quot;ymin&quot;: 37.7820000000001,
        ///                    &quot;xmax&quot;: -122.402715,
        ///                    &quot;ymax&quot;: 37.785718,
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleSolveResults {
            get {
                return ResourceManager.GetString("SampleSolveResults", resourceCulture);
            }
        }
    }
}
